[Settings]

[build]
  ignore = "git log -1 --pretty=%B | grep renovate"


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
