name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mbround18/paws/actions/paws-up@main
        with:
          github-token: ${{ github.token }}

      - name: Build & test
        run: paws ci --toolchain node
