name: Release

on: [release]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            .yarn/*
            !.yarn/patches
            !.yarn/releases
            !.yarn/plugins
            !.yarn/sdks
            !.yarn/versions
            .pnp.*
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Build
        env:
          NODE_ENV: production
        run: yarn generate

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/

  release:
    runs-on: ubuntu-latest
    environment: Netlify
    needs: generate
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: actions/checkout@v2
        with:
          path: (package.json|yarn.lock)

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            .yarn/*
            !.yarn/patches
            !.yarn/releases
            !.yarn/plugins
            !.yarn/sdks
            !.yarn/versions
            .pnp.*
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: Publish
        run: |
          yarn netlify deploy --prod --dir=dist     \
          --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}  \
          --site ${{ secrets.NETLIFY_SITE_ID }}
