name: Version

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: mbround18/paws/actions/paws-up@main
        with:
          github-token: ${{ github.token }}
          install-dagger: "false"

      - name: Tag & release
        id: semver
        run: paws semver --push --branch main

      - name: Changelog
        run: paws changelog --commit --branch main
